### ISSUE TITLE
Rename binary to rexical

### ISSUE THREAD

**Issue by balasankarc** [sparklemotion/rexical#13]
Hi,
I am packaging rexical for Debian. There seems to be a slight issue; there exists a package named rex. So, the binary of rexical which is also named rex causes a conflict. I saw the commit message saying moving to rexical from rex but the file inside bin folder is still named rex. Can you please rename that to rexical?

Thanks.

**Comment by flavorjones** [comment]
We're unlikely to change the name at this point, since the executable has been named `rex` since before this particular gem existed (and before rubygems existed!). It would be a breaking change for every user.
