### ISSUE TITLE
Longest match first

### ISSUE THREAD

**Issue by v0dro** [sparklemotion/rexical#17]
In lex, the longest match is given preference irrespective of it's position in the rules file. This does not seem to be the case with rexical. For example, given the following rules:

```
class TestLanguage
rule
  u     { puts "Single u." }
  uu    { puts "Double u." }
end
```

... and the output `"uu"`, the output is `"Single u."` twice, and not `"Double u."` as expected.

**Comment by sonots** [comment]
+1 

Given the following rules:

```
class Fluent::FilterWhere::Parser
macro
  NonQuotedIdentifier [a-zA-Z$][a-zA-z0-9\.\-_]*
rule
  NOT                   { [:NOT, text] }
  {NonQuotedIdentifier} { [:IDENTIFIER, text] }
```

`nothing` becomes :NOT (`not`) and :IDENTIFIER (`hing`) although I expected :IDENTIFIER (`nothing`).

**Comment by flavorjones** [comment]
Unfortunately, this is simply how rexical (and before it, rex) works. For this lexer, if you look at the generated code you'll see something like this:

```ruby
def _next_token
          text = @ss.peek(1)
          @lineno  +=  1  if text == "\n"
          token = case @state
            when nil
          case
                  when (text = @ss.scan(/u/))
                     action { puts "Single u." }

                  when (text = @ss.scan(/uu/))
                     action { puts "Double u." }


          else
            text = @ss.string[@ss.pos .. -1]
            raise  ScanError, "can not match: '" + text + "'"
          end  # if
```

The `case` statement is constructed by emitting `when` clauses in the order that the rules were defined.

Unfortunately, we're unlikely to change how rules are applied at this point. Changing how rules are matched now, after so many years, would almost certainly be a breaking change. I hope you're able to work around this by ordering your rules in your rex file.
