### ISSUE TITLE
Issue with reserved word 'end'

### ISSUE THREAD

**Issue by SergioTeranZ** [sparklemotion/rexical#22]
in my `.rex` file i have a rule like

`end                   {[:END,[text,nil]]}`

and it seems to have a problem when it generates the `.rb` file, the reserved word close the class before it actually ends.

**Comment by flavorjones** [comment]
Please make sure your pattern (in your case, I mean `end`) does not appear at the start of the line. The line will be parsed correctly as a rule so long as there is some whitespace before it.

```
   end { [:END, [text, nil]] }
```

should work.

**Comment by SergioTeranZ** [comment]
thanks, I figure that out eventually...5 years ago.
