### ISSUE TITLE
Why I met this error?

### ISSUE THREAD

**Issue by morris2015** [sparklemotion/rexical#24]
Hi Tenderlove,

Thank you for provide this sample. 

But I met error when I try the underlying command in bash:
racc calc3.racc
rex  calc3.rex
ruby calc3.tab.rb

The first 2 commands are OK. But the 3rd one 'ruby calc3.tab.rb' produces the following errors:
===
Traceback (most recent call last):
        2: from calc3.tab.rb:12:in `<main>'
        1: from /usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- calc3.rex (LoadError)

===
Whlie of course the required file 'calc3.rex' is in the same dir.

Why?

Any suggestion is appreciated.
Thanks,

Morris

**Comment by zenspider** [comment]
There is not enough information provided for anyone to help.

Presumably on line 12 there is a require that doesn't make sense.

**Comment by flavorjones** [comment]
Please try `ruby -I. calc3.tab.rb` to resolve the require.
