### ISSUE TITLE
getoptlong Usage

### ISSUE THREAD

**Issue by gremerritt** [sparklemotion/rexical#28]
The following warning is raised under Ruby 3.3.1:

> /Users/me/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30: warning: /Users/me/.rbenv/versions/3.3.1/lib/ruby/3.3.0/getoptlong.rb was loaded from the standard library, but will no longer be part of the default gems since Ruby 3.4.0. Add getoptlong to your Gemfile or gemspec. Also contact author of rexical-1.0.7 to add getoptlong into its gemspec.

**Comment by tenderlove** [comment]
Hi, thanks for filing this.  I don't really use this gem anymore and I'm not very interested in maintaining it.  I've opened issue #29 to address that situation.

In the mean time, if you're willing to send a PR that fixes this bug, I'll merge it.

**Comment by flavorjones** [comment]
Fixed in v1.0.8
